### ISSUE TITLE
pcregrep Error -46 while using simple recursive regex 

### ISSUE THREAD

**Issue by michaeltyson** [PhilipHazel/pcre2#24]
Hi!

This regex:

`
(((?>[^()]+)|(?R))*)
`

Causes pcregrep/pcre2grep to bail immediately with error -46:

```
> pcre2grep '(((?>[^()]+)|(?R))*)' test.txt
pcre2grep: pcre2_match() gave error -46 while matching this text:
...
```

**Comment by zherczeg** [comment]
I cannot check it without a some kind of input. Anyway, #22 might fix this. Could you check it?

**Comment by zherczeg** [comment]
Hm, this pattern looks really like an unbound regex, since it recursively call itself without matching anything.

Regex1010 also complains: https://regex101.com/r/qqLt6Z/1
The match was halted because your expression contains a recursive loop. This means either that the whole pattern, or a subpattern, has been called recursively for the second time at the same position in the subject string.

**Comment by michaeltyson** [comment]
Ah, okay, fair enough. I was just using it as I found it Out There On The Internet and it seemed to be being presented as an accepted technique for recursively matching bracket pairs. Guess I need to keep digging.
